### ISSUE TITLE
Add refresh icon

### ISSUE THREAD

**Issue by dragonjet** [shinycolors/shinycwp#1]
As requested from facebook, in case there is loading error, stuck, or any thing they needed to refresh the game.

**Comment by shinycwp** [comment]
Thanks. Will look to it. Currenly I don't have much place to put buttons, but I'm thinking of a custom title bar and removing the window frame so I can add some there.

**Comment by shinycwp** [comment]
added in 9c9c758431f777fe42a11031b519c45eb4f688b1
